### ISSUE TITLE
not implemented documented functionality

### ISSUE THREAD

**Issue by dunaevai135** [JakeSmokie/CSLabs#2]
Task says: 

> В любой момент времени пользователь может вернуться к любому месту вычислений,
введя вместо операции номер соответствующего значения.

present behavior:
```
[#4] = 0.
@: +
> 11
[#5] = 11.
@: #4
Wrong input. Try again.
@: 4 
Wrong input. Try again.
```

**Comment by JakeSmokie** [comment]
Use `#` as operator, then type index of calculated operation.

**Comment by dunaevai135** [comment]
> ‘#’ followed with number of evaluation step

corresponds to
```
[#2] = 8
@: /
> 2
[#3] = 4
@: #2
[#4] = 8
@: *
> 10
[#5] = 80
```
Change "Usage" path.
